# Generated by Django 4.2.11 on 2025-01-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bhavcopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_code', models.IntegerField()),
                ('sc_name', models.CharField(max_length=100)),
                ('sc_group', models.CharField(max_length=10)),
                ('sc_type', models.CharField(max_length=10)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prev_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_trades', models.IntegerField()),
                ('no_of_shrs', models.BigIntegerField()),
                ('net_turnov', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tdcloindi', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
