# Generated by Django 4.2.11 on 2025-01-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataext', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhavcopy',
            old_name='sc_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='bhavcopy',
            old_name='sc_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='net_turnov',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='no_of_shrs',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='no_trades',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='prev_close',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='sc_group',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='sc_type',
        ),
        migrations.RemoveField(
            model_name='bhavcopy',
            name='tdcloindi',
        ),
    ]
