# Generated by Django 4.2.11 on 2025-01-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataext', '0002_rename_sc_code_bhavcopy_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhavcopy',
            name='close',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bhavcopy',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bhavcopy',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bhavcopy',
            name='open',
            field=models.FloatField(default=0),
        ),
    ]
